load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "gmock1",
    srcs = ["gmock1.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gmock2",
    srcs = ["gmock2.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gmock3",
    srcs = ["gmock3.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gmock4",
    srcs = ["gmock4.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gmock5",
    srcs = ["gmock5.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)


cc_test(
    name = "gmock6",
    srcs = ["gmock6.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)