cc_test(
  name = "folly_test",
  srcs = [
    "MPMCQueueTest.cpp",
    "DeterministicSchedule.h",
    "DeterministicSchedule.cpp",
  ],
  deps = [
    "//third_party/folly:folly",
    "//third_party/folly:benchmark",
    "//third_party/folly:testutil",
    "//third_party/gflags",
    "//external:gtest",
  ],
)
